// Generated by scripts/sync-i18n-assets.mjs — do not edit manually.

export const PROMPT_PACKS_V1 = {
  "ar": {
    "locale": "ar",
    "label": "العربية",
    "llmCapability": "ui-only",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "de-DE": {
    "locale": "de-DE",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "en-AU": {
    "locale": "en-AU",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "en-GB": {
    "locale": "en-GB",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "en-US": {
    "locale": "en-US",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "es-ES": {
    "locale": "es-ES",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "fr-FR": {
    "locale": "fr-FR",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "he": {
    "locale": "he",
    "label": "עברית",
    "llmCapability": "ui-only",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "it-IT": {
    "locale": "it-IT",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "nl-NL": {
    "locale": "nl-NL",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "pl-PL": {
    "locale": "pl-PL",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "pt-BR": {
    "locale": "pt-BR",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  },
  "pt-PT": {
    "locale": "pt-PT",
    "label": "English (UK)",
    "llmCapability": "full",
    "strings": {
      "motd.system": "You write one short, simple quote about healthy living for a health tracking app. Topics: sleep, water, gentle movement, rest, fresh air, balanced food, or stress relief. Use plain everyday words. Max 18 words. No names. No medical advice. No quotation marks. Reply with only the quote sentence.",
      "motd.user": "Write one healthy-lifestyle quote.",
      "summary.system": "You summarise health tracking data for the patient in exactly 2 short sentences. Use only the data provided. Mention 1-2 specific findings. Be clear and encouraging. Reply with only the summary text.",
      "suggest.system": "You write one short sentence for a daily health log note. Compare today to the recent average. Use only the data provided. Reply with only the note sentence.",
      "context.improving": "Improving: {metrics}.",
      "context.worsening": "Worsening: {metrics}.",
      "context.stable": "Stable: {metrics}.",
      "context.dataLine": "{dayCount} day(s) of data.",
      "context.flares": "Flares: {count} day(s).",
      "context.topStressor": "Top stressor: {name}{pct}."
    }
  }
};

