import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export type ChartExportRow = { label: string; value: string };

export async function printOrShareChartReport(options: {
  title: string;
  viewLabel: string;
  rangeLabel: string;
  rows: ChartExportRow[];
  radarSvg?: string;
}): Promise<void> {
  const tableRows = options.rows
    .map((r) => `<tr><td>${escapeHtml(r.label)}</td><td>${escapeHtml(r.value)}</td></tr>`)
    .join('');
  const radarBlock = options.radarSvg
    ? `<div style="text-align:center;margin:16px 0">${options.radarSvg}</div>`
    : '';
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${escapeHtml(options.title)}</title></head><body style="font-family:system-ui,sans-serif;padding:24px;color:#222">
<h1>${escapeHtml(options.title)}</h1>
<p><strong>View:</strong> ${escapeHtml(options.viewLabel)} · <strong>Range:</strong> ${escapeHtml(options.rangeLabel)}</p>
${radarBlock}
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;margin-top:12px">
<thead><tr><th>Metric</th><th>Summary</th></tr></thead>
<tbody>${tableRows}</tbody>
</table>
<p style="margin-top:24px;font-size:12px;color:#666">Generated by Rianell for clinician sharing.</p>
</body></html>`;
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: options.title,
    });
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Inline SVG spider chart for PDF embedding (Plan 09 C6). */
export function buildRadarSvgForExport(
  labels: string[],
  values: number[],
  size = 220
): string {
  if (labels.length < 3 || values.length !== labels.length) return '';
  const cx = size / 2;
  const cy = size / 2;
  const maxR = size * 0.38;
  const count = labels.length;
  const angleAt = (i: number) => (-Math.PI / 2) + (i * 2 * Math.PI) / count;
  const pointAt = (i: number, radius: number) => {
    const a = angleAt(i);
    return { x: cx + radius * Math.cos(a), y: cy + radius * Math.sin(a) };
  };
  const rings = [0.25, 0.5, 0.75, 1]
    .map((frac) => {
      const pts = Array.from({ length: count }, (_, i) => {
        const p = pointAt(i, maxR * frac);
        return `${p.x.toFixed(1)},${p.y.toFixed(1)}`;
      });
      return `<polygon points="${pts.join(' ')}" fill="none" stroke="#ccc" stroke-width="1"/>`;
    })
    .join('');
  const axes = Array.from({ length: count }, (_, i) => {
    const p = pointAt(i, maxR);
    return `<line x1="${cx}" y1="${cy}" x2="${p.x.toFixed(1)}" y2="${p.y.toFixed(1)}" stroke="#ddd" stroke-width="1"/>`;
  }).join('');
  const dataPts = values
    .map((v, i) => {
      const r = (Math.max(0, Math.min(10, v)) / 10) * maxR;
      const p = pointAt(i, r);
      return `${p.x.toFixed(1)},${p.y.toFixed(1)}`;
    })
    .join(' ');
  const labelsSvg = labels
    .map((label, i) => {
      const p = pointAt(i, maxR + 14);
      return `<text x="${p.x.toFixed(1)}" y="${p.y.toFixed(1)}" text-anchor="middle" font-size="9" fill="#444">${escapeHtml(label.slice(0, 16))}</text>`;
    })
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">${rings}${axes}<polygon points="${dataPts}" fill="rgba(76,175,80,0.25)" stroke="#4caf50" stroke-width="2"/>${labelsSvg}</svg>`;
}
